<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OppoUnlockToolbox</RootNamespace>
    <AssemblyName>OppoUnlockToolbox</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Product>OPPO 解锁工具箱</Product>
    <Company></Company>
    <Version>0.1.1</Version>
    <FileVersion>0.1.1</FileVersion>
    <AssemblyTitle>OPPO 解锁工具箱</AssemblyTitle>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\author.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OppoUnlockToolbox.Core\OppoUnlockToolbox.Core.csproj" />
  </ItemGroup>

</Project>
